spring.application.name=Backend-LiveTogether

spring.datasource.url=jdbc:postgresql://dpg-d6s3nh9aae7s73d3ncb0-a.frankfurt-postgres.render.com/livetogether_ojim
spring.datasource.username=livetogether_ojim_user
spring.datasource.password=klufgFwrYat0PbvpWvNoQRIkZlcazPpV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

application.security.jwt.secret-key=H59gjsTiZkrnrFkrYvUIg17llruY1EQaKsqUobrrza0=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=livetogether2005@gmail.com
spring.mail.password=ltqu udqt bnbj liqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true