spring.application.name=Backend-LiveTogether

spring.datasource.url=jdbc:postgresql://dpg-d811tme7r5hc73c3juag-a.frankfurt-postgres.render.com/livetogether_2n7q
spring.datasource.username=livetogether_2n7q_user
spring.datasource.password=BdFzI3OwcEwPSuRDuVhtlkbMj0mvr9wC
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG

application.security.jwt.secret-key=H59gjsTiZkrnrFkrYvUIg17llruY1EQaKsqUobrrza0=

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=livetogether2005@gmail.com
spring.mail.password=ltqu udqt bnbj liqq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true